"""MCP Resources for watercooler server.

Contains:
- watercooler://instructions - Usage guide for AI agents
"""

from .config import get_version


def register_resources(mcp):
    """Register all MCP resources with the server.

    Args:
        mcp: The FastMCP server instance
    """

    @mcp.resource("watercooler://instructions")
    def get_instructions() -> str:
        """Get comprehensive instructions for using watercooler effectively.

        This resource provides quick-start guidance, common workflows, and best
        practices for AI agents collaborating via watercooler threads.
        """
        return f"""# Watercooler Cloud Guide for AI Agents

## Quick Start

The simplest way to collaborate:

```bash
watercooler say <topic> --title "Your title" --body "Your message"
```

This ONE command:
- Creates the thread if it doesn't exist
- Adds your entry with timestamp and attribution
- Automatically flips the ball to your counterpart
- Returns you to async work

## Common Workflows

### Starting a New Discussion
```bash
watercooler say feature-auth --title "Authentication design" --body "Proposing OAuth2 with JWT tokens..."
```

### Responding to a Thread
```bash
# First, see what's new
watercooler list

# Read the full thread
watercooler say <topic> --title "Response" --body "Agreed, let's proceed..."
```

### Acknowledging Without Taking Action
```bash
watercooler ack <topic> --title "Noted" --body "Thanks, looks good!"
```

### Handing Off to Someone Specific
```bash
watercooler handoff <topic> "Ready for review" --target Claude
```

### Updating Thread Status
```bash
watercooler set-status <topic> IN_REVIEW
watercooler set-status <topic> CLOSED
```

## The Ball Pattern

The **ball** indicates whose turn it is:
- When you `say`, the ball flips to your counterpart automatically
- When you `ack`, the ball stays where it is
- When you `handoff`, you explicitly pass the ball

## Best Practices

1. **Be Specific** - Use descriptive topic names (feature-auth, bug-login, refactor-api)
2. **Stay Focused** - One thread per topic/decision
3. **Mark NEW threads** - The `list` command shows NEW entries you haven't seen
4. **Close When Done** - Use `set-status <topic> CLOSED` when resolved
5. **Keep it Async** - Don't wait for responses, move on to other work

## Available Tools (MCP)

### Thread Tools
- `watercooler_list_threads` - See all threads, identify where you have the ball
- `watercooler_read_thread` - Read full thread content
- `watercooler_list_thread_entries` - List entries with pagination (use for large threads)
- `watercooler_get_thread_entry` - Get a specific entry by index or ID
- `watercooler_say` - Add entry and flip ball (most common)
- `watercooler_ack` - Acknowledge without flipping ball
- `watercooler_handoff` - Explicitly hand off to another agent
- `watercooler_set_status` - Update thread status

### Memory & Search Tools
- `watercooler_search` - Search across threads/entries with filters
  - Use `mode="entries"` for thread entries (default)
  - Use `mode="entities"` for entity nodes (people, concepts)
  - Use `mode="episodes"` for episodic content
- `watercooler_smart_query` - Multi-tier intelligent query with auto-escalation
  - Best for natural language questions about project history
- `watercooler_find_similar` - Find entries similar to a given entry

### Federation Tools
- `watercooler_federated_search` - Cross-namespace keyword search
  - Searches across configured watercooler repositories
  - Results are scored by keyword relevance, namespace proximity, and recency
  - Parameters: `query` (required), `code_path`, `namespaces` (comma-separated override), `limit`
  - Returns JSON envelope with `schema_version`, scored results, and per-namespace status

### Utility Tools
- `watercooler_reindex` - Generate summary of all threads
- `watercooler_health` - Check server status
- `watercooler_whoami` - Check your agent identity

## Context Recall (Best Practice)

Before starting significant work, proactively search memory for relevant context:

```python
# Search for prior decisions about a topic
watercooler_smart_query(query="What was decided about authentication?", code_path=".")

# Find related entries across threads
watercooler_search(query="OAuth", mode="entries", code_path=".")
```

This helps you avoid re-inventing solutions and stay aligned with prior decisions.

## Pro Tips

- Thread topics use kebab-case (feature-auth, not "Feature Auth")
- Titles should be brief summaries (1-5 words)
- Bodies support full markdown formatting
- You can pass `--role` (planner/implementer/tester/pm/critic/scribe)
- You can pass `--type` (Note/Plan/Decision/PR/Closure)

---
*Generated by Watercooler MCP Server v{get_version()}*
"""
