"""Unit tests for the tether / warrant-thinness read model (#881, Unit 4).

Tethers are support categories, not truth labels. These tests pin the
derivation rules, the thin-support threshold, the no-collapsed-confidence
contract, and the deterministic rendering helpers.
"""

from watercooler import authority_support as asup


class TestBuildReadModel:
    def test_empty_evidence_is_thin_and_unknown(self):
        model = asup.build_read_model([])
        assert model.support_counts == {}
        assert model.dominant_tether == "unknown"
        assert model.thin_support is True
        assert model.thin_support_reason is not None

    def test_counts_are_per_tether_not_collapsed(self):
        model = asup.build_read_model(
            [
                {"tether": "source", "label": "verified_quote"},
                {"tether": "interpretive", "label": "generated_extraction"},
                {"tether": "interpretive", "label": "extractor_warning"},
            ]
        )
        # Counts stay per-tether — no single confidence number on the model.
        assert model.support_counts == {"source": 1, "interpretive": 2}
        assert not hasattr(model, "confidence")
        assert not hasattr(model, "score")

    def test_dominant_tether_breaks_ties_by_canonical_order(self):
        # source and user both have count 1; source is stronger (earlier).
        model = asup.build_read_model(
            [
                {"tether": "user", "label": "human_authorized"},
                {"tether": "source", "label": "verified_quote"},
            ]
        )
        assert model.dominant_tether == "source"

    def test_dominant_is_strongest_substantive_not_most_frequent(self):
        # interpretive has the higher raw count, but source is substantive and
        # stronger — dominant_tether must report source, not interpretive.
        model = asup.build_read_model(
            [
                {"tether": "interpretive", "label": "a"},
                {"tether": "interpretive", "label": "b"},
                {"tether": "source", "label": "verified_quote"},
            ]
        )
        assert model.dominant_tether == "source"

    def test_dominant_falls_back_to_strongest_present_when_no_substantive(self):
        model = asup.build_read_model(
            [
                {"tether": "unknown", "label": "missing"},
                {"tether": "interpretive", "label": "a"},
            ]
        )
        # interpretive is stronger than unknown in canonical order.
        assert model.dominant_tether == "interpretive"

    def test_support_counts_iterate_in_canonical_order(self):
        # Rendering relies on canonical insertion order — lock it down.
        model = asup.build_read_model(
            [
                {"tether": "interpretive", "label": "a"},
                {"tether": "user", "label": "human_authorized"},
                {"tether": "source", "label": "verified_quote"},
            ]
        )
        assert list(model.support_counts) == ["source", "user", "interpretive"]

    def test_substantive_support_is_not_thin(self):
        model = asup.build_read_model(
            [{"tether": "source", "label": "verified_quote"}]
        )
        assert model.thin_support is False
        assert model.thin_support_reason is None

    def test_test_and_contract_tethers_are_substantive(self):
        for tether in ("test", "contract"):
            model = asup.build_read_model(
                [{"tether": tether, "label": f"{tether}_support"}]
            )
            assert model.support_counts == {tether: 1}
            assert model.dominant_tether == tether
            assert model.thin_support is False
            assert model.thin_support_reason is None

    def test_interpretive_only_is_thin(self):
        model = asup.build_read_model(
            [{"tether": "interpretive", "label": "generated_extraction"}]
        )
        assert model.thin_support is True

    def test_unknown_tether_is_coerced_and_does_not_inflate_substantive(self):
        model = asup.build_read_model(
            [{"tether": "world_truth", "label": "spoofed"}]
        )
        # An unrecognized tether must never count as substantive support.
        assert model.support_counts == {"unknown": 1}
        assert model.thin_support is True
        assert model.support_evidence[0]["tether"] == "unknown"


class TestDeriveCandidateSupport:
    def test_verified_source_quote_is_source_supported_not_thin(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["we decided to use FalkorDB"],
            quote_verified=True,
        )
        # A generated candidate with a verified source quote is source-supported
        # and is NOT thin solely because it was generated by an LLM.
        assert model.support_counts.get("source") == 1
        assert model.support_counts.get("interpretive") == 1  # generated_extraction
        assert model.thin_support is False
        assert model.dominant_tether == "source"
        # Evidence carries an inspectable source pointer.
        source_ev = [e for e in model.support_evidence if e["tether"] == "source"]
        assert source_ev and source_ev[0]["entry_id"] == "01SRC0000000000000000000AA"
        assert "quote_hash" in source_ev[0]

    def test_no_source_no_owner_only_inference_is_thin(self):
        model = asup.derive_candidate_support(
            source_entry_id=None,
            verbatim_quotes=[],
            quote_verified=False,
        )
        assert model.thin_support is True
        # Only interpretive + unknown support present.
        assert set(model.support_counts) <= {"interpretive", "unknown"}
        assert "unknown" in model.support_counts  # missing_quote_evidence

    def test_unverified_quotes_are_interpretive_not_source(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["a quote the LLM invented"],
            quote_verified=False,
        )
        assert "source" not in model.support_counts
        assert model.thin_support is True
        labels = {e["label"] for e in model.support_evidence}
        assert "unverified_quote" in labels

    def test_human_authorized_is_user_support(self):
        model = asup.derive_candidate_support(
            source_entry_id=None,
            verbatim_quotes=[],
            quote_verified=False,
            human_authorized_by="github:caleb",
        )
        assert model.support_counts.get("user") == 1
        assert model.thin_support is False  # user is substantive support
        user_ev = [e for e in model.support_evidence if e["tether"] == "user"]
        assert user_ev and user_ev[0]["detail"] == "github:caleb"

    def test_decision_source_entry_is_record_state_support(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["quote"],
            quote_verified=True,
            source_entry_type="Decision",
        )
        assert model.support_counts.get("record_state") == 1

    def test_record_state_withheld_when_quotes_unverified(self):
        # Codex P2 regression: a Decision/Closure source must NOT grant
        # record_state support when the quote evidence failed validation —
        # otherwise a hallucinated-quote candidate reads as record-backed.
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["a quote the LLM invented"],
            quote_verified=False,
            source_entry_type="Decision",
        )
        assert "record_state" not in model.support_counts
        assert "source" not in model.support_counts
        assert model.thin_support is True

    def test_record_state_withheld_when_no_quotes(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=[],
            quote_verified=False,
            source_entry_type="Closure",
        )
        assert "record_state" not in model.support_counts
        assert model.thin_support is True

    def test_record_state_with_human_owner_but_unverified_quotes(self):
        # At promotion a weak-quote candidate from a Decision source still gets
        # NO record_state (unverified tie), but human ownership makes it non-thin.
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["unverified"],
            quote_verified=False,
            source_entry_type="Decision",
            human_authorized_by="github:caleb",
        )
        assert "record_state" not in model.support_counts
        assert model.support_counts.get("user") == 1
        assert model.thin_support is False

    def test_warning_and_moral_flag_add_interpretive(self):
        base = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["quote"],
            quote_verified=True,
        )
        enriched = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["quote"],
            quote_verified=True,
            extractor_warning="ambiguous scope",
            moral_delegation_warning=True,
        )
        assert enriched.support_counts["interpretive"] > base.support_counts[
            "interpretive"
        ]

    def test_counts_not_capped_by_evidence_display_cap(self):
        # Codex P2 regression: support_counts is the primary surface and must
        # report the true number of supports, not the render cap. The model also
        # retains every evidence pointer for inspection.
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=[f"quote {i}" for i in range(5)],
            quote_verified=True,
        )
        assert model.support_counts["source"] == 5
        source_ev = [e for e in model.support_evidence if e["tether"] == "source"]
        assert len(source_ev) == 5


class TestRendering:
    def test_quote_hash_is_stable_and_whitespace_insensitive(self):
        assert asup.quote_hash("a  b") == asup.quote_hash("a b")
        assert asup.quote_hash("x") == asup.quote_hash("x")
        assert asup.quote_hash("x") != asup.quote_hash("y")

    def test_markers_include_counts_dominant_thin(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["quote"],
            quote_verified=True,
        )
        markers = asup.render_support_markers(model)
        joined = "\n".join(markers)
        assert "Tether-Support-Counts:" in joined
        assert "Dominant-Tether:" in joined
        assert "Thin-Support: false" in joined
        # No collapsed confidence number in the markers.
        assert "Confidence" not in joined

    def test_markers_report_uncapped_counts(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=[f"quote {i}" for i in range(5)],
            quote_verified=True,
        )
        markers = "\n".join(asup.render_support_markers(model))
        assert "source=5" in markers

    def test_section_caps_displayed_pointers_but_shows_true_count(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=[f"quote {i}" for i in range(5)],
            quote_verified=True,
        )
        section = "\n".join(asup.render_support_section(model))
        # The per-tether count line shows the true total...
        assert "- source: 5" in section
        # ...but the inspectable pointer list is capped, with an omission note.
        assert section.count("source · verified_quote") == asup._MAX_EVIDENCE_PER_TETHER
        assert "more source pointer" in section

    def test_thin_marker_carries_reason(self):
        model = asup.build_read_model([])
        markers = "\n".join(asup.render_support_markers(model))
        assert "Thin-Support: true" in markers
        assert "Thin-Support-Reason:" in markers

    def test_section_warns_support_is_not_world_truth(self):
        model = asup.derive_candidate_support(
            source_entry_id="01SRC0000000000000000000AA",
            verbatim_quotes=["quote"],
            quote_verified=True,
        )
        section = "\n".join(asup.render_support_section(model))
        assert "## Support tethers" in section
        # The section must distinguish record/source support from external truth.
        assert "not" in section.lower() and "true in the world" in section.lower()
        assert "Support evidence:" in section
